<?php

use App\Models\MailTemplate;
use App\Models\MailTemplateTranslation;
use Illuminate\Database\Migrations\Migration;

class AddAuthSSOWelcomeMailTemplate extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $mailTemplate = new MailTemplate();
        $mailTemplate->app_id = 0;
        $mailTemplate->type = 'AuthSSOWelcome';
        $mailTemplate->save();

        $mailTemplateTranslation = new MailTemplateTranslation();
        $mailTemplateTranslation->mail_template_id = $mailTemplate->id;
        $mailTemplateTranslation->language='de';
        $mailTemplateTranslation->title = 'Registrierungsbestätigung für %appname%';
        $mailTemplateTranslation->body = "Hallo %username%,
Vielen Dank für die Registrierung zum %appname%.

Dein Nutzername: %username%

Viel Spaß und viel Erfolg beim Quiz!
Dein %appname% Team


Bitte antworte nicht auf diese E-Mail, da es sich um eine vom System generierte E-Mail handelt.
Support: %contact-mail% | %contact-phone%

Teilnahme- und Nutzungsbedingungen:
%tos%";
        $mailTemplateTranslation->save();

        $mailTemplateTranslation = new MailTemplateTranslation();
        $mailTemplateTranslation->mail_template_id = $mailTemplate->id;
        $mailTemplateTranslation->language='en';
        $mailTemplateTranslation->title = 'Confirmation of registration for %appname%';
        $mailTemplateTranslation->body = "Hello %username%,
Many thanks for registering for %appname%.


Your username: %username%

Good luck with the quiz and have fun!

Your %appname% Team

Please do not reply to this email as it has been generated by the system.

Support: %contact-mail% | %contact-phone%

Terms and conditions of participation and use:

%tos%";
        $mailTemplateTranslation->save();

        $mailTemplateTranslation = new MailTemplateTranslation();
        $mailTemplateTranslation->mail_template_id = $mailTemplate->id;
        $mailTemplateTranslation->language='jp';
        $mailTemplateTranslation->title = '%appname% の登録完了通知';
        $mailTemplateTranslation->body = "こんにちは %username%、
%appname% への登録ありがとう。

あなたのユーザー名は:%username%

クイズを楽しんで、頑張って！
あなたの %appname% チームより

このメールはシステムにより送信されました。返信はしないでください。
サポート: %contact-mail% | %contact-phone%

参加条件と利用規約：
%tos%";
        $mailTemplateTranslation->save();

        $mailTemplateTranslation = new MailTemplateTranslation();
        $mailTemplateTranslation->mail_template_id = $mailTemplate->id;
        $mailTemplateTranslation->language='pt';
        $mailTemplateTranslation->title = 'Confirmação de registo para %appname%';
        $mailTemplateTranslation->body = "Olá, %username%,
Muito obrigado por se registar no %appname%

O seu nome de utilizador: %username%

Desejamos muito sucesso e diversão com o Quiz!
A sua equipe %appname%

Este e-mail gerado automaticamente pelo sistema, é favor não responder.
Suporte: %contact-mail% | %contact-phone%

Condições de participação e utilização:
%tos%";
        $mailTemplateTranslation->save();

        $mailTemplateTranslation = new MailTemplateTranslation();
        $mailTemplateTranslation->mail_template_id = $mailTemplate->id;
        $mailTemplateTranslation->language='tr';
        $mailTemplateTranslation->title = '%appname% için kayıt onayı';
        $mailTemplateTranslation->body = "Merhaba %username%,
%appname% kaydı için çok teşekkür ederiz.

Kullanıcı adın: %username%

Bilgi yarışmasında iyi eğlenceler ve başarılar dileriz!
%appname% Ekibin


Lütfen bu e-postaya cevap verme, çünkü bu sistem tarafından oluşturulan bir e-postadır.
Destek: %contact-mail% | %contact-phone%

Katılım ve kullanım şartları:
%tos%";
        $mailTemplateTranslation->save();

        $mailTemplateTranslation = new MailTemplateTranslation();
        $mailTemplateTranslation->mail_template_id = $mailTemplate->id;
        $mailTemplateTranslation->language='ru';
        $mailTemplateTranslation->title = 'Подтверждение регистрации для %appname%';
        $mailTemplateTranslation->body = "Привет %username%,
Спасибо за регистрацию в %appname%.

Ваш логин: %username%

Удачи и успехов в квизе!
Ваша команда %appname%

Не отвечайте на это письмо, так как оно создано системой автоматически.
Поддержка: %contact-mail% | %contact-phone%

Условия участия и использования:
%tos%";
        $mailTemplateTranslation->save();

        $mailTemplateTranslation = new MailTemplateTranslation();
        $mailTemplateTranslation->mail_template_id = $mailTemplate->id;
        $mailTemplateTranslation->language='zh';
        $mailTemplateTranslation->title = '%appname% 注册确认';
        $mailTemplateTranslation->body = "您好 %username%，
非常感谢注册 %appname%。

您的用户名：%username%

愿愉快地测验，祝您好运！
您的 %appname% 团队

请勿答复此电子邮件，因为这是系统生成的电子邮件。
支持：%contact-mail% | %contact-phone%

参见和使用条款：
%tos%";
        $mailTemplateTranslation->save();

        $mailTemplateTranslation = new MailTemplateTranslation();
        $mailTemplateTranslation->mail_template_id = $mailTemplate->id;
        $mailTemplateTranslation->language='pl';
        $mailTemplateTranslation->title = 'Potwierdzenie rejestracji dla %appname%';
        $mailTemplateTranslation->body = "Witaj %username%,
Dziękujemy za zarejestrowanie się w %appname%.

Twoja nazwa użytkownika: %username%

Miłej zabawy i powodzenia w rozwiązywaniu quizów!
Twój zespół %appname%

Prosimy nie odpowiadać na ten e-mail, ponieważ jest to wiadomość generowana przez system.
Wsparcie: %contact-mail% | %contact-phone%

Warunki uczestnictwa i użytkowania:
%tos%";
        $mailTemplateTranslation->save();

        $mailTemplateTranslation = new MailTemplateTranslation();
        $mailTemplateTranslation->mail_template_id = $mailTemplate->id;
        $mailTemplateTranslation->language='it';
        $mailTemplateTranslation->title = 'Conferma di registrazione per %appname%';
        $mailTemplateTranslation->body = "Ciao %username%,
        grazie per esserti registrato su %appname%.

        Il tuo nome utente: %username%

        Buon divertimento e buona fortuna con il quiz!
        La tua squadra %appname%

        Non rispondere a questa e-mail, poiché si tratta di una e-mail generata dal sistema.
        Supporto: %contact-mail% | %contact-phone%

        Condizioni di partecipazione e di utilizzo:
        %tos%";
        $mailTemplateTranslation->save();

        $mailTemplateTranslation = new MailTemplateTranslation();
        $mailTemplateTranslation->mail_template_id = $mailTemplate->id;
        $mailTemplateTranslation->language='de_formal';
        $mailTemplateTranslation->title = 'Registrierungsbestätigung für %appname%';
        $mailTemplateTranslation->body = "Hallo %username%,
Vielen Dank für die Registrierung zum %appname%.

Ihr Nutzername: %username%

Viel Spaß und viel Erfolg beim Quiz!
Ihr %appname% Team

Bitte antworten Sie nicht auf diese E-Mail, da es sich um eine vom System generierte E-Mail handelt.
Support: %contact-mail% | %contact-phone%

Teilnahme- und Nutzungsbedingungen:
%tos%";
        $mailTemplateTranslation->save();

        $mailTemplateTranslation = new MailTemplateTranslation();
        $mailTemplateTranslation->mail_template_id = $mailTemplate->id;
        $mailTemplateTranslation->language='es';
        $mailTemplateTranslation->title = 'Confirmación del registro en %appname%';
        $mailTemplateTranslation->body = "Hola %username%:
Muchas gracias por registrarse en %appname%.

Su nombre de usuario: %username%

¡Esperamos que disfrute y coseche grandes éxitos en el juego de preguntas y respuestas!
Su equipo de %appname%

Le rogamos que no responda a este correo electrónico, ya que se trata de un mensaje generado por el sistema.
Asistencia: %contact-mail% | %contact-phone%

Condiciones de participación y de uso:
%tos%";
        $mailTemplateTranslation->save();

        $mailTemplateTranslation = new MailTemplateTranslation();
        $mailTemplateTranslation->mail_template_id = $mailTemplate->id;
        $mailTemplateTranslation->language='fr';
        $mailTemplateTranslation->title = 'Confirmation d’inscription à %appname%';
        $mailTemplateTranslation->body = "Bonjour %username%,
Merci pour l'inscription à %appname%.

Votre nom d'utilisateur : %username%

Amusez-vous bien et bonne chance avec le quiz !
Votre équipe %appname%

Veuillez ne pas répondre à ce courriel, car il s'agit d'un courriel généré par le système.
Support : %contact-mail% | %contact-phone%

Conditions de participation et d'utilisation :
%tos%";
        $mailTemplateTranslation->save();


    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        $mailTemplate = MailTemplate::where('type', '=', 'AuthSSOWelcome')
            ->where('app_id', 0)
            ->first();
        MailTemplateTranslation::where('mail_template_id' ,'=', $mailTemplate->id)->delete();
        $mailTemplate->delete();
    }
}
