name: CI
# Controls when the action will run.
on:
    # Triggers the workflow on push events but only for the staging branch
    push:
        branches: [ staging, master ]
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
# unfortunately we must set concurrency at workflow level:
# > Note: When concurrency is specified at the job level,
# > order is not guaranteed for jobs or runs that queue within 5 minutes of each other.
concurrency:
    group: ci-${{ github.ref }}
    cancel-in-progress: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    docker:
        runs-on: ubuntu-latest
        outputs:
            imagetag: ${{ steps.setimagetag.outputs.imagetag }}
        steps:
            - uses: actions/checkout@v2

            - uses: actions/cache@v2
              id: npm-cache
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Cache Docker layers
              uses: actions/cache@v2
              with:
                  path: /tmp/.buildx-cache
                  key: ${{ runner.os }}-buildx-$imagetag
                  restore-keys: |
                      ${{ runner.os }}-buildx-

            - name: Setup buildx
              uses: docker/setup-buildx-action@v1
              id: buildx
              with:
                  install: true

            - name: Docker Login
              uses: docker/login-action@v1.9.0
              with:
                  registry: 'keelearning.azurecr.io'
                  username: 'keelearning'
                  password: ${{ secrets.AZURECR_TOKEN }}
                  logout: true

            - uses: actions/setup-node@v2
              with:
                  node-version: '18'

            - run: npm ci

            -
                name: Set image tag
                id: setimagetag
                run: |
                    imagetag="${committag////_}"
                    echo "imagetag=$imagetag" >> $GITHUB_ENV
                    echo "::set-output name=imagetag::$imagetag"
                env:
                    committag: ${{ github.ref }}-${{ github.sha }}

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: keelearning.azurecr.io/keelearning/keelearning-php-backend/nginx-php-fpm:${{ env.imagetag }}
                  cache-from: type=local,src=/tmp/.buildx-cache
                  cache-to: type=local,dest=/tmp/.buildx-cache-new
                  file: docker/nginx-php-fpm/Dockerfile
                  context: .

            -
                # Temp fix
                # https://github.com/docker/build-push-action/issues/252
                # https://github.com/moby/buildkit/issues/1896
                name: Move cache
                run: |
                    rm -rf /tmp/.buildx-cache
                    mv /tmp/.buildx-cache-new /tmp/.buildx-cache
    deploy:
        if: github.ref == 'refs/heads/staging'
        needs: docker
        runs-on: ubuntu-latest
        steps:
            - name: Install kubectl
              uses: Azure/setup-kubectl@v2.0
              with:
                  version: 'v1.19.3'

            - name: Deploy to k8s (staging)
              run: |
                  kubectl config set-cluster k8s --server="${{ secrets.KUBE_URL }}" --insecure-skip-tls-verify=true
                  kubectl config set-credentials keelearningde --token="${{ secrets.KUBE_TOKEN }}"
                  kubectl config set-context default --cluster=k8s --user=keelearningde
                  kubectl config use-context default
                  kubectl patch deployment backend -nkeelearning-staging -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"$(date +'%s')\"}},\"spec\":{\"containers\":[{\"name\":\"backend\",\"image\":\"keelearning.azurecr.io/keelearning/keelearning-php-backend/nginx-php-fpm:${{ needs.docker.outputs.imagetag }}\"}]}}}}"
                  kubectl patch deployment horizon -nkeelearning-staging -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"$(date +'%s')\"}},\"spec\":{\"containers\":[{\"name\":\"horizon\",\"image\":\"keelearning.azurecr.io/keelearning/keelearning-php-backend/nginx-php-fpm:${{ needs.docker.outputs.imagetag }}\"}]}}}}"
